### ISSUE TITLE
No such file or directory: 'data/ocdIDs/'

### ISSUE THREAD

**Issue by agrueneberg** [CodeforBirmingham/Open-Disclosure#69]
When running make:

```
python3 DataFetcher.py
Downloading: http://fcpa.alabamavotes.gov/PublicSite/Docs/BulkDataDownloads/2015_CashContributionsExtract.csv.zip
Extracting file into 2015_CashContributionsExtract.csv.zip...done!

Downloading: http://fcpa.alabamavotes.gov/PublicSite/Docs/BulkDataDownloads/2015_InKindContributionsExtract.csv.zip
Extracting file into 2015_InKindContributionsExtract.csv.zip...done!

Downloading: http://fcpa.alabamavotes.gov/PublicSite/Docs/BulkDataDownloads/2015_ExpendituresExtract.csv.zip
Extracting file into 2015_ExpendituresExtract.csv.zip...done!

Downloading: http://fcpa.alabamavotes.gov/PublicSite/Docs/BulkDataDownloads/2015_OtherReceiptsExtract.csv.zip
Extracting file into 2015_OtherReceiptsExtract.csv.zip...done!

python3 PartyFetcher.py
Writing party data to Parties.csv
python3 GenerateTransactees.py
>> Loading data from 2015_CashContributionsExtract.csv
>> Loading data from 2015_ExpendituresExtract.csv
>> Loading data from 2015_InKindContributionsExtract.csv
>> Loading data from 2015_OtherReceiptsExtract.csv
>> Writing 17476 records to 2015_Transactees.json
python3 GenerateParties.py
>> Loading data from 2015_CashContributionsExtract.csv
>> Loading data from 2015_ExpendituresExtract.csv
>> Loading data from 2015_InKindContributionsExtract.csv
>> Loading data from 2015_OtherReceiptsExtract.csv
>> Modified 337 party records with additional info.
>> Writing 540 records to Parties.json
python3 GenerateTransactions.py
>> Loading 2015_Transactees.json...17476 records loaded.
>> Loading data from 2015_CashContributionsExtract.csv
>> Loading data from 2015_ExpendituresExtract.csv
>> Loading data from 2015_InKindContributionsExtract.csv
>> Loading data from 2015_OtherReceiptsExtract.csv
>> Writing 25212 records to 2015_Transactions.json
python3 GenerateDistricts.py
Traceback (most recent call last):
  File "GenerateDistricts.py", line 49, in <module>
    main()
  File "GenerateDistricts.py", line 26, in main
    OCDID_FILES = os.listdir(OCDID_DIR)
FileNotFoundError: [Errno 2] No such file or directory: 'data/ocdIDs/'
Makefile:15: recipe for target 'organize' failed
make: *** [organize] Error 1
```

**Comment by mleeds95** [comment]
This doesn't happen to me. Are you running it from the utils directory? Is '/' the correct path separator for your OS? Are you sure you're branch is up to date with origin/master?

**Comment by agrueneberg** [comment]
Oops, I didn't realize that ocdIDs and map are now contained in the data folder. I used to delete the data folder once I wanted to fetch more recent data.

**Comment by mleeds95** [comment]
Yeah you should switch to using make clean.
